#+setupfile: ./hugo_setup.org
#+hugo_slug: A_brief_history_of_Western_Philosophy_by_Anthony_Kenny_in_2019
#+TITLE: A brief history of Western Philosophy by Anthony Kenny in 2019
* 1. Philosophy in its infancy
** 1.1 The Milesians
** 1.2 Xenophanes
** 1.3 Heraclitus
** 1.4 The school of Parmenides
** 1.5 Empedocles
** 1.6 The Atomists
* 2. The Athens of Socrates
** 2.1 The Athenian Empire
** 2.2 Anaxagoras
** 2.3 The sophists
** 2.4 Socrates
** 2.5 The __Euthyphro__
** 2.6 The __Crito__
** 2.7 The __Phaedo__
* 3. The philosophy of Plato
** 3.1 Life and works
** 3.2 The theory of ideas
** 3.3 Plato's republic
** 3.4 The Theaetetus and the Sophist
* 4. The system of Artistotle
** 4.1 Plato's pupil, Alexander's teacher
** 4.2 The foundation of logic
** 4.3 The theory of drama
** 4.4 Moral philosophy: virtue and happiness
** 4.5 Moral philosophy: wisdom and understanding
** 4.6 Politics
** 4.7 Science and explanation
** 4.8 Words and things
** 4.9 Motion and change
** 4.10 Soul, sense, and intellect
** 4.11 Metaphysics
* 5. Greek philosophy after Aristotle
** 5.1 The Hellenistic Era
** 5.2 Epicureanism
** 5.3 Stoicism
** 5.4 Scepticism
** 5.5 Rome and its empire
** 5.6 Jesus of Nazareth
** 5.7 Christianity and Gnosticism
** 5.8 Neo-Platonism
* 6. Early Christian philosophy
** 6.1 Arianism and Orthodoxy
** 6.2 The theology of incarnation
** 6.3 The life of Augustine
** 6.4 The City of God and the Mystery of Grace
** 6.5 Boethius and Philoponus
* 7. Early Medieval philosophy
** 7.1 John the Scot
** 7.2 Alkindi and Avicenna
** 7.3 The Feudal system
** 7.4 Saint Anselm
** 7.5 Abelard and Heloise
** 7.6 Abelard's logic
** 7.7 Abelard's ethics
** 7.8 Averroes
* 8. Philosophy in the Thirteenth century
** 8.1 An age of innovation
** 8.2 Sain Bonaventure
** 8.3 Thirteenth-Century logic
** 8.4 Aquinas' life and works
** 8.5 Aquinas' natural theology
** 8.6 Matter, form, substance, and accident
** 8.7 Aquinas on essence and existence
** 8.8 Aquinas' Philosophy of Mind
** 8.9 Aquinas' Moral Philosophy
* 9. Oxford philosophers
** 9.1 The Fourteenth-Century University
** 9.2 Duns Scotus
** 9.3 Ockham's logic of language
** 9.4 Ockham's political theory
** 9.6 The Oxford calculators
** 9.7 John Wyclif
* 10. Renaissance philosophy
** 10.1 The renaissance
** 10.2 Free-will: Rome vs. Louvain
** 10.3 Renaissance Platonism
** 10.4 Machiavelli
** 10.5 More's Utopia
** 10.6 The Reformation
** 10.7 Post-Reformation Philosophy
** 10.8 Bruno and Galileo
** 10.9 Francis Bacon
* 11. The age of Descartes
** 11.1 The wars of religion
** 11.2The life of Descartes
** 11.3 The doubt and the __Cogito__
** 11.4 The essence of mind
** 11.5 God, mind, and body
** 11.6 The material world
* 12. English philosophy in the Seventeenth Century
** 12.1 The Empiricism of Thomas Hobbes
** 12.2 Hobbes' political philosophy
** 12.3 The political theory of John Locke
** 12.4 Locke on ideas and qualities
** 12.5 Substances and persons
* 13. Continental philosophy in the age of Louis XIV
** 13.1 Blaise Pascal
** 13.2 Spinoza and Malebranche
** 13.3 Leibniz
* 14. British philosophy in the Eighteenth century
** 14.1 Berkeley
** 14.2 Hume's Philosophy of Mind
** 14.3 Hume on causation
** 14.4 Reid and Common Sense
* 15. The Enlightenment
** 15.1 The __Philosophes__
** 15.2 Rousseau
** 15.3 Revolution and romanticism
* 16. The critical philosophy of Kant
** 16.1 Kant's Copernican Revolution
** 16.2 The Transcendental Aesthetic
** 16.2 The Transcendental Analytic: The Deduction of the Categories
** 16.3 The Transcendental Dialectic: The Paralogisms of Pure Reason
** 16.4 The Transcendental Dialectic: The Antinomies of Pure Reason
** 16.5 The Transcendental Dialectic: The Critique of Natural Theology
** 16.6 Kant's Moral Philosophy
* 17. German Idealism and Materialism
** 17.1 Fichte
** 17.2 Hegel
*** The subject matter of logic is **the Absolute, the totality of reality,** familiar to us from earlier philosophers as **Being**. We start from the thesis that the Absolute is pure Being. But pure Being without any qualities is nothing; so we are led to the antithesis ‘The Absolute is nothing’. This thesis and antithesis are overcome by synthesis: __the union of Being and Unbeing is becoming__, and so we say **‘The Absolute is Becoming’.**
*** Hegel does make use of Aristotle’s definition of God when he describes the Absolute as being the Thought which thinks itself. But it turns out that the self-awareness of the Absolute comes at the end, not at the beginning, of this life-cycle, and it is brought into existence by the philosophical reflection of human beings. It is the history of philosophy which brings the Absolute face to face with itself.
** 17.3 Marx and the Young Hegelians
*** Marx divided the past, present, and future history of the relations of production into six phases: primitive communism, slavery, feudalism, capitalism, socialism, and ultimate communism
*** He based this conclusion on two economic theories: the labour theory of value, and the theory of surplus value.
*** Under capitalism, however, prices in the market are determined not by true value, but by supply and demand. The capitalist, who owns the raw material and the means of production, having paid the worker a wage equal to his day’s subsistence, say 1, can often sell the product for many times that sum, say 10. The difference between the subsistence wage and the market price is the surplus value, in this case 9. Under capitalism, no part ofthis surplus value is returned to the worker, it is all pocketed by the employer. The effect is that only one-tenth ofthe labourer’s work is for his own benefit; nine-tenths of it is just to produce profit for the capitalist.
** 17.4 Capitalism and its discontents
* 18. The Utilitarians
** 18.1 Jeremy Bentham
** 18.2 The Utilitarianism of J.S. Mill
** 18.3 Mill's Logic
* 19. Three Nineteenth-Century Philosophers
** 19.1 Schopenhauer
** 19.2 Kierkegaard
** 19.3 Nietzsche
* 20. Three Modern Masters
** 20.1 Charles Darwin
** 20.2 John Henry Newman
** 20.3 Sigmund Freud
* 21. Logic and the foundations of mathematics
** 21.1 Frege's logic
** 21.2 Frege's logicism
** 21.3 Frege's philosophy of logic
** 21.4 Russell's paradox
** 21.5 Russell's theory of descriptions
** 21.6 Logical analysis
* 22. Continental philosophy in the early twentieth century
** 22.1 Henri Bergson
** 22.2 Husserl's phenomenology
*** [[file:Edmund_Husserl.org][Edmund Husserl]]
** 22.3 The existentialism of Heidegger
** 22.4 The existentialism of Sartre and de Beauvoir
* 23. The philosophy of Wittgenstein
** 23.1 __Tractatus Logico-Philosophicus__
*** Its central doctrine is the picture theory of meaning. According to this theory, language consists of propositions which picture the world. Propositions are the perceptible expressions of thoughts, and thoughts are logical pictures of facts; the world is the totality of facts.
** 23.2 Logical positivism
** 23.3 __Philosophical investigations__
* 24. Recent continental philosophy
** 24.1 The Frankfurt School
** 24.2 Jacques Derrida
** 24.3 [[file:Jurgen_Habermas.org][Jurgen Habermas]]
* 25. Recent analytic philosophy
** 25.1 Elizabeth Anscombe
** 25.2 W.V.O. Quine
** 25.3 Donald Davidson
*** a satisfactory theory of meaning must give an account of how the meanings of sentences depend upon the meanings of words
** 25.4 Peter Geach
** 25.5 Peter Strawson
** 25.6 American metaphysics
** 25.7 The Cartesian revival
*** Philosophers who have been convinced by Wittgenstein see qualia as just the latest example of the ineffable private experiences that the private language argument was supposed to have killed off. But certainly in the United States many philosophers appear comfortable with the idea, and it has been passed on also to neuroscientists, many of whom have thereby become unconscious dualists. Many philosophers and psychologists believe that the task of a scientific theory of the mind is to establish a principle of correlation between the occurrence of mental states and processes and the occurrence of states and processes in the brain. This correlation would only be a possibility if mental events (e.g. thoughts, or flashes of understanding) were them? selves measureable in the way in which physical events are measurable.
** 25.8 Analytical ethics
** 25.9 John Rawls
** 25.10 [[file:Richard_Rorty.org][Richard Rorty]]
*** Mainstream, systematic philosophy aims at truth, but there is another form of philosophy that aims at self-formation, which Rorty styles ‘edification’. **Edification** is a project of finding new, better, more interesting, more fruitful ways of speaking. Edifying philosophers are sceptical about systematic philosophy.
*** ‘Great systematic philosophers, like great scientists, build for eternity. Great edifying philosophers destroy for the sake of their own generation.’
*** one can concede to [Rorty] that Descartes did great damage to philosophy by giving it an epistemological turn without agreeing that the damage is irreparable. It is, in fact, possible to return to the pre-Cartesian, Aristotelian conception of human nature, and it is perfectly arguable that this was what that great edifier Wittgenstein actually achieved.
*** ‘What has to be overcome is not a difficulty of the understanding, but of the will. The job to be done is really a job on oneself.’
