#+setupfile: ./hugo_setup.org
#+hugo_slug: A_free_energy_principle_for_a_particular_physics_by_Karl_Friston_in_2019
#+TITLE: A free energy principle for a particular physics by Karl Friston in 2019
* [[file:variational_inference.org][variational inference]]
* 0. Introduction
** We assume that for something to exist it must possess (internal or intrinsic) states that can be separated statistically from (external or extrinsic) states that do not constitute the thing.
** the states of things (i.e., particles) comprise mixtures of blanket states, where the Markov blanket surrounds things at a smaller scale
** the Langevin formulation of dynamics – at any given spatiotemporal scale – can be decomposed into an ensemble of Markov blankets. These blanket states have a dynamics at a higher scale with exactly the same (Langevin) form as the dynamics of the original scale. When lifting the dynamics from one scale to the next, internal states are effectively eliminated, leaving only slow, macroscopic dynamics of blanket states. These become the states of things at the next level, which have their own Markov blankets and so on. The endpoint of this formalism is a description of everything at progressively higher spatial and temporal scales. The implicit separation of temporal scales is used in subsequent sections to examine the sorts of dynamics, physics or mechanics of progressively larger things.
** Organization
*** part 1: basic results
**** constraints on the dynamics of Markov blankets that possess measurable characteristics
**** **measurability as a constraint** requires the existence of an invariant measure (in the sense of Ergodic theory) over sufficiently long periods of time within the context of the dynamics of the system under consideration
***** Consider a measurable space $$(X, \Sigma)$$
****** Example
******* Let $$X = \{ 1, 2, 3 \}$$ and let $$\Sigma = \mathcal{P}(X)$$
******* Let $$X = \{ 1, 2, 3 \}$$ and let $$\Sigma = \{ X, \emptyset \}$$
***** A function $$\mu \colon \Sigma \rightarrow \mathbb{R}$$ is a measure if it satisfies
****** non-negativity, null set-maps-to-zero, and countable additivity 
***** Let $$f \colon X \rightarrow X$$ be a measurable function on the measurable space $$(X, \Sigma)$$. A measure $$\mu$$ is invariant under $$f$$ if $$\forall A \in \Sigma$$, $$\mu(f^{-1}(A))= \mu(A)$$
***** general invariant measures can be formulated in terms of the push forward as
****** $$ f_* (\mu) = \mu $$
***** the collection of invariant measures on $$X$$ with respect to a given function $$f$$ is denoted $$M_f(X)$$
**** 
*** part 2: apply basic results to limiting cases of dynamical systems to recover quantum, statistical, and classical mechanics
*** part 3: special case of active systems in terms of `Bayesian mechanics` for particles with internal states that correlate with the distribution of interactions those particles have with their respective environments
* 1. The setup
** 1.1 Something or nothing
*** Some preliminaries
**** Langevin
**** Path integral
**** Fokker-Planck
*** Nonequilibrium steady states
**** the action of any path can be expressed in terms of a motion-dependent (kinetic) term, a (path* independent) term – that depends upon the change in surprisal – and a (path-dependent) term that scales with the amplitude of random fluctuations
*** Fluctuations and information length
**** 
*** [[file:random_dynamical_systems.org][random dynamical systems]] and Markov blankets
*** Markov blankets and marginal
*** Summary
** 1.2 Symmetry breaking and self-organization
*** Self-organization and self-evidencing
*** Self-organization, frustration, and supersymmetry
*** Self-organization and information length
** 1.3 Synthetic soups and active matter
*** An active soup
*** A random dynamical attractor and its Markov blankets
*** The Markov blanket
*** The emergence of order
*** Summary
** 1.4 States, particles, and fluctuations
*** Starting at the end
*** The Markovian partition
*** The adiabatic reduction
*** Elimination and renormalization
*** Summary
* 2. Some special cases
** 2.1 A theory of small things * quantum mechanics
*** The Schrodinger equation from first principles
*** Wave particle duality and the de Broglie hypothesis
*** Heisenberg uncertainty principle
*** Inference, measurement and wave function collapse?
*** Summary
** 2.2 A theory of lots of little things * statistical mechanics
*** Stochastic thermodynamics
*** Stochastic energetics
*** Fluctuation theorems
*** Summary
** 2.3 A theory of big things * classical mechanics
*** Conservative systems
*** Random fluctuations and generalized motion
*** Summary
* 3. A particular case
** 3.1 A theory of autonomous things * Bayesian mechanics
*** Risk and ambiguity
*** Inference and measurement
*** Information geometry
*** Variational Bayes
*** Summary
** 3.2 Simulating sentience
*** The representation of order
*** Summary
** 3.3 Active inference and self-evidencing
*** Active inference with continuous states
*** Active inference with discrete states
*** Deep inference: gradient flows or least action?
*** Summary
** 3.4 The thermodynamics of inference
*** Potentials and surprisal
*** Ensemble free energies
*** Summary
** Discussion
*** Conclusion
* Appendices
** A. Stratonovich path integrals
** B. Lemmas and proofs
** C. Nonequilibrium steady-state energy functions
** D. the Fokker-Planck operator
** E. Generalized motion
** F. Discrete state-space models
