#+setupfile: ./hugo_setup.org
#+hugo_slug: A_tutorial_on_the_free-energy_framework_for_modeling_perception_and_learning_by_Rafal_Bogacz_in_2017
#+TITLE: A tutorial on the free-energy framework for modeling perception and learning by Rafal Bogacz in 2017
* [[file:papers.org][papers]], [[file:free_energy_principle.org][free energy principle]], [[file:probabilistic_inference.org][probabilistic inference]]
* 1. Introduction
** The model of Friston (2005) and the [[file:predictive_coding_model.org][predictive coding model]] of Rao and Ballard (1999) provide a powerful mathematical framework to describe how the sensory cortex extracts information from noisy stimuli. The [[file:predictive_coding_model.org][predictive coding model]] (Rao & Ballard, 1999) suggests that visual cortex infers the most likely properties of stimuli from noisy sensory input.
** Friston's model added the explicit representation of uncertainy to the [[file:predictive_coding_model.org][predictive coding model]] framework
*** learning about the variance and covariance of features can also be implemented by simple synaptic plasticity rules
*** the perceptual system may differentially weight sources of sensory information depending on their level of noise
*** sensory networks can learn to recognize features encoded in patterns of covariance between inputs
*** it provides a natural way to implement attentional modulation as the reduction in variance of attended features
*** this model can be viewed as an approximate Bayesian inference based on minimization of the so-called "free-energy" function
** Any computational model would need to satisfy the following constraints to be considered biologically plausible
*** 1. Local computation: A neuron performs computations only on the basis of the activity of its input neurons and synaptic weights associated with these inputs (rather than information encoded in other parts of the circuit).
*** 2. Local plasticity: Synaptic plasticity is only based on the activity of pre-synaptic and post-synaptic neurons.
** Outline of the paper
*** 2. Introduces the model using a very simple example and with simple mathematical concepts for the purpose of maximizing accessibility
*** 3. provides mathematical foundations for the model and shows how the inference in the model is related to minimizing free-energy
*** 4. Application to biological neural networks: scaling up the model to describe sensory cortex
*** 5. An extension of the Friston 2005 model that satisfies the constraint of local plasticity
* 2. Simplest example of perception
** 2.0 Introduction
*** Consider attempting to infer the size of an object $$v$$ from light intensity $$u$$ where the relationship providing the expected value of light intensity from object size is given by $$ g(v) = v^2 $$.
*** The likelihood of observing a given light intensity given a particular object is then
**** $$p(u \vert v) = f(u;\; g(v), \, \Sigma_u)$$
*** We would now like to invert this relationship to estimate the probability of a particular object size given an observation: $$ p(v \vert u)$$.
** 2.1 Exact solution
*** 
* 3. Scaling up the model of perception
* 4. Local plasticity
* 5. Discussion
