#+setupfile: ./hugo_setup.org
#+hugo_slug: Bayesian_informal_logic_and_fallacy_by_Kevin_Korb_in_2003
#+TITLE: Bayesian informal logic and fallacy by Kevin Korb in 2003
#+roam_tags: medicine papers
* [[file:probabilistic_inference.org][probabilistic inference]], [[file:philosophy.org][philosophy]], [[file:logic.org][logic]], [[file:papers.org][papers]]
* Korb, K. (2004). Bayesian Informal Logic and Fallacy. __Informal Logic__, __24__(1), 41–70. https://doi.org/10.22329/il.v24i1.2132
* Abstract: Bayesian reasoning has been applied formally to statistical inference, machine learning and analysing scientific method. Here I apply it informally to more common forms of inference, namely natural language arguments. I analyse a variety of traditional fallacies, deductive, inductive and causal, and find more merit in them than is generally acknowledged. Bayesian principles provide a framework for understanding ordinary arguments which is well worth developing.
* Applying bayesian inference to natural language arguments is related to a concept I have thought of in the past as folk probability being applied with significant bias in real-time in various decision-making situations.
* I would be interested to connect this with [[file:Bayesian_approaches_to_clinical_trials_and_health-care_evaluation_by_David_Spiegelhalter,_Keith_Abrams,_and_Jonathan_Myles_in_2004.org][Bayesian approaches to clinical trials and health-care evaluation by David Spiegelhalter, Keith Abrams, and Jonathan Myles in 2004]] in the context of folk probability in medicine.
