#+setupfile: ./hugo_setup.org
#+hugo_slug: Intelligence_and_spirit_by_Reza_Negarestani_in_2018
#+TITLE: Intelligence and spirit by Reza Negarestani in 2018
* [[file:philosophy.org][philosophy]], [[file:Bayesian_brain_hypothesis.org][Bayesian brain hypothesis]], [[file:predictive_coding_model.org][predictive coding model]], [[file:books.org][books]], [[file:Reza_Negarestani.org][Reza Negarestani]]
* reviews
** [[https://tripleampersand.org/stupidity-geist-review-intelligence-spirit-reza-negarestani/][Stupidity & Geist: A Review of Intelligence and Spirit by Reza Negarestani * &&& Journal&&& Journal]]
*** Hegelian tributaries, Sellarsian currents and Turing tides previously stemmed by a conceptual blockage so immense as to constitute a fatberg of thought. This stagnation is down to nothing more than academic philosophy’s attendant failure to adequately address the historical decoupling of intelligence and mind enacted by computation.
*** This spirit of connective thought did not thaw off until the last decade or two, in which a productive interplay between computer science, mathematics, logic, cognitive science, and philosophy has once again emerged. It is this new constellation which I&S playfully explores, delving into themes such as complexity and algorithmic information theory, predictive coding and posthumanism, with all the sobriety of an infant in Legoland.
*** The emphasis on interaction in semantics places I&S in close proximity to the late Putnam, whose notion of socio-functionalism sowed the seeds of Negarestani’s account, while the focus on normativity and pragmatism echoes much of Brandom’s work. While it maintains strong continuities with these positions, the text attempts a novel fusion of neural materialism with the semantic inferentialism of the Pittsburgh School
*** The book offers a meaningful contrast to one such neural model – predictive processing (PP), a dominant contemporary theory of mind which places cognition in a probabilistic Bayesian frame. Where PP follows experimental data closely, mirrors techniques in AI, and is bound to inductive logic, I&S emphasizes sapience, logical inference and the formal autonomy of language – but both center the role of generative models.
*** On reasoning, I&S offers a multi-level account of inference which is incompatible with that offered by hierarchical Bayesian priors, but there are gaps in both accounts which invite considerable speculation. The two also differ at the level of philosophical project and the attendant political implications – one engaged in positing a generalized form of intelligence in all its sociality, whereas the other concerns itself with modelling the cognition of individual human minds.
*** Rather than buckle and give way to a critique of computability, I&S rises to the challenge to elaborate a parallel account of intelligence and computation, imbricating both in its rendering of reason as a recognitive capacity. The reader is asked to suspend judgement until the account is developed in full, the book clearly exhibiting a sensitivity to a plethora of computationalist traps. It issues its own challenges to inductivism, superintelligence, pan-computation and game theory along the way, constantly engaged in deflating claims afflicted by various dogmas – be they Humanist, Bayesian, or Darwinist in origin.
*** Navigating intelligence through the dimly lit alleys of our own minds, unbinding it from the errors and biases placed on it by our own ‘natural’ languages, aiding its evasion of the various pitfalls and dead-ends we unwittingly place in its path – this is the political task posed by a philosophy of intelligence, what Negarestani calls “the labor of the inhuman”. The book is a support vector for this journey, equal parts manual, experiment and schema – no less than a guide to the pre-history of intelligence.
*** Girard’s logic of Ludics is brought into the ambit of interactionist paradigms in computer science, while a correspondence between proofs and programs is embraced to offer a constructive theory of meaning. The immanent unfolding of semantics from syntactic structures is rendered an open-ended dialogic game and interaction is foregrounded as a properly formal condition of reason.
*** Undecidability isn’t given the proper treatment deserving of a computationalist position, while claims as to the logical basis of language lack Brandom’s nuance and will raise skepticism in readers not convinced by Carnap’s account. In contrast to PP, recent developments in cognitive science are underplayed. It calls for the decolonization of thought but fails to engage with key thinkers of the inhuman such as Wynter or Fanon.
*** But back to the question of arrival. The text arrives at our laps and screens in an age of viral stupidity, spontaneous consensus, and automated bias. The apotheosis of Châtelet’s ‘cyber-wolves’ – those self-appointed princes of the network, from Peter Thiel to Bruno Latour – marks a hegemony in which all forms of minded beings find themselves embedded.
*** I&S tasks us with new ways of thinking intelligence – to consider how formalisms generate their own autonomy, how language is inextricably computational, how interaction bridges syntax and semantics, and finally how selfhood and learning, agency and freedom, can be cultivated in this environment.
*** It challenges the reader to envision the emancipatory potential of an inhumanist account of intelligence, realized by a novel model of computation born of interaction.
*** https://diigo.com/0i703l
* discussion group from New Centre
** [[https://www.youtube.com/watch?v=QnXG5CyRIPc&list=PLkk0hVJrhEd97x2po4tj81iG0NKSXXHlL&index=2&t=1225s][Transcendental Computationalism: Reading Intelligence and Spirit * Beginning of content in first meeting embedded within the playlist of all meetings]]
* contents
** 1. Between conception and transformation
*** It is only what it does, 1; 
*** Functions and Multilevel Structural Constraints, 11; 
*** Functional Integration: Phases of Geist, 19; 
*** Self-Relation: A Function in Progress, 26; 
*** Self-Consciousness as Conception and Transformation in an Objective World, 35; 
*** A Series of Transformations, 44; 
*** History as the Elaboration of What it Means to Be an Artefact of the Concept, 46; 
*** A Note on Theory, Mind’s Structuring Function, and Ratiocinating Powers, 51; 
*** Selves as Functional Items as Artefacts of Mind, 54; 
*** The Sapience Controversy, 56; 
*** Rational Integration, Judgement, and Generation of Further Abilities, 62; 
*** Historical Awareness as an Essential Constructive and Critical Ability, 65; 
*** The Dasein of Geist, 67; 
*** The Necessary and Sufficient Links Between Conception and Transformation, 73; 
*** Geist at the Edge of Intelligibility, 77
** 2. An outside view of ourselves as experimental AGI
** 3. This I, or We, or It, the thing which speaks (forms of intuition)
** 4. Some unsettling Kantian news as delivered by Boltzmann (an excursion into time)
** 5. This I, or We, or It, the thing which speaks (objectivity of thought)
** 6. This I, or We, or It, the thing which speaks (Dasein of Geist)
** 7. This I, or We, or It, the thing which speaks (language as interaction as computation)
** 8. Philosophy of intelligence
** Appendix: Quandaries of induction in philosophy of knowledge, philosophy of mind, and artificial intelligence
