#+setupfile: ./hugo_setup.org
#+hugo_slug: Introductory_Lectures_on_Stochastic_Population_Systems_by_Donald_Dawson_in_2017
#+TITLE: Introductory Lectures on Stochastic Population Systems by Donald Dawson in 2017
* Model categories
    1. fixed number of finitely many types
    2. varying number of finitely many types?
    3. fixed number of infinitely many types
    4. varying number of infinitely many types
* 6. Infinitely many types models
** 6.1 Introduction
*** 6.1.1 Motivation [[file:key_subsection.org][key subsection]]
**** We have considered particle systems above with finitely many types. In the 1970’s with the advent of electrophoresis and molecular biology, new models were needed in which the number of types were not fixed. In many cases the number of types can be random and new types can be introduced at random times. Several models began to appear at that time involving infinitely many types, for example the ladder or stepwise mutation model of Ohta and Kimura (1973) [465] (which could model for example continuous characteristics). Another model was one in which no attempt to model the structure of types was made but in which new types can be introduced (leading to the infinitely many alleles model) (Kimura and Crow (1964) [362]). In this model we take [0, 1] as the type space. Then when a new type is needed we can choose a type in [0, 1] by sampling from the uniform distribution on [0, 1]. The infinitely many sites model introduced by Kimura in 1969 provides an idealization of the genome viewed as a sequence of nucleotides (A,T,C,G). These processes now form the basis for molecular population genetics. 

More generally, such ^^infinitely many type models^^ provide the possibility of ^^coding information at a number of levels^^ and provide a powerful tool for the ^^study of complex systems^^. For example we can code ^^historical information, genealogical information, and information about the random environment^^ that has been visited. In addition it ^^allows for individuals with internal structure described by an internal state space and state transition dynamics^^.
** 
