#+setupfile: ./hugo_setup.org
#+hugo_slug: John_Hopfield
#+TITLE: John Hopfield
* Hopfield, J. J. (2014). Whatever Happened to Solid State Physics? __The Annual Review of Condensed Matter Physics Is Annu. Rev. Condens. Matter Phys. 2014__, __5__, 1–13. https://doi.org/10.1146/annurev-conmatphys-031113-133924
** What is physics? To me—growing up with a father and mother who were both physicists—physics was not subject matter. The atom, the troposphere, the nucleus, a piece of glass, the washing machine, my bicycle, the phonograph, a magnet—these were all incidentally the subject matter. The central idea was that the world is understandable, that you should be able to take anything apart, understand the relationships between its constituents, do experiments, and on that basis be able to develop a quantitative understanding of its behavior. Physics was a point of view that the world around us is, with effort, ingenuity, and adequate resources, understandable in a predictive and reasonably quantitative fashion. Being a physicist is a dedication to the quest for this kind of understanding.
