#+setupfile: ./hugo_setup.org
#+hugo_slug: Jurgen_Habermas
#+TITLE: Jurgen Habermas
* pathologies of modernity ushered in by the enlightenment
* using reason to question foundations leads to the questioning reason itself
* Adorno and Horkheimer argued the enlightenment placed too much emphasis on reason
* Human activity is divided by Habermas into two kinds: **instrumental action** and **communicative action**
** **Instrumental action** is purposive activity that aims at a predetermined end and chooses means that are causally effective of the end. 
** The output of **communicative action**, on the other hand, is something that is not predetermined in advance, and is not brought about by causal means. The paradigm of communicative action is action that is brought about by speech and achieves a consensus of understanding.
* The concept of communicative action is the key to understanding the nature of society. Society, like action, takes a dual form, which can be called **‘system’** and **‘lifeworld’.**
** The **system** is the __locus__ of **instrumental action**, and 
** the **lifeworld** is the __locus__ of **communicative action**. The lifeworld consists of the natural and informal institutions of social life: family, friendships, the social groups that make up the public sphere.
* The tensions between the lifeworld and system in modern society means, according to Habermas, that modernity is an ‘unfinished project’. We cannot return to pre-modern society, and sacrifice the increased knowledge, the economic benefits, and the expanded freedom that modernity has brought. On the other hand, in a secular era, modernity has not yet succeeded in developing the social and moral norms which would suffice to protect the lifeworld from colonization by the system.
* Discourse is an important concept for Habermas. He uses the word to mean a privileged language-game, whose aim is to achieve a rationally motivated consensus.
