#+setupfile: ./hugo_setup.org
#+hugo_slug: Large_deviations_and_dynamical_phase_transitions_in_stochastic_chemical_networks_by_Lazarescu_and_Esposito_in_2019
#+TITLE: Large deviations and dynamical phase transitions in stochastic chemical networks by Lazarescu and Esposito in 2019
* [[file:papers.org][papers]], [[file:stochastic_processes.org][stochastic processes]], [[file:chemical_reaction_network_theory.org][chemical reaction network theory]], [[file:large_deviations.org][large deviations]]
* I. Introduction
** **Chemical reaction networks** are **linear Markov jump processes** on a **composition space** $$\mathbb{N}^N$$ where $$N$$ is the number of chemical species.
** We describe the large deviation behavior of generic chemical reaction networks, starting from the chemical master equation74 which describes their microscopic dynamics. This **paper aims at being pedagogical and self-contained**, and therefore contains many formulae and derivations that are not entirely necessary for practical computations of, say, large deviation functions of time-averaged currents
** Section II. we introduce those models, along with a few important concepts to analyze them, and we define the **mesoscopic variables** that will be relevant in the **large-volume limit**
** Section III. we **take the said large-volume limit** and show that the **dynamics of those systems can be described through a path integral** with a Lagrangian that can be computed explicitly. That **path integral is dominated by a trajectory solving an Euler-Lagrange equation** or equivalently Hamilton’s equations for an appropriate Hamiltonian.
** Section IV. application of the previously developed formalism to compute the SCGF of currents and densities of the model class under consideration, which is the Legendre transform of the large deviation function of stationary currents and densities. Systems whose deterministic equations have several attractors (i.e., that are multistable) generically undergo first-order dynamical phase transitions around small values of the dynamical biases.
** Section V. exhibition of a few of those dynamical phase transitions in variants of a simple bistable system called the Schlögl model
** Section VI. hands-on summary of how one may compute large deviation functions of dynamical observables in a chemical reaction network, meant as a quick reference or a minimal guide
* II. Definition of the microscopic process and observables
** A. Definition of the process
*** $$N$$ species $$A_x$$ for $$x \in [[0, N[[$$
*** microscopic state (vector) $$n$$ with components $$n_x$$ given by the number of indistinguishable particles of each species 
*** volume $$V$$
*** chemical reactions whereby a set of reactants is destroyed and replaced by a set of products defines a Markov jump process on the state-space $$\mathbb{N}^N$$
*** $$\gamma$$ are all sets of particles occurring on either side of a reaction referred to as __complexes__
*** $$\nu^{\gamma}_x$$ are __stoichiometric coefficients__ defining the number of particles of species $$A_x$$ in complex $$\gamma$$
*** the reaction destroying complex $$\gamma$$ and creating complex $$\gamma'$$ is
**** $$ \sum_x \nu^{\gamma}_x A_x \rightarrow \sum_x \nu^{\gamma'}_x A_x$$
*** the rate at which this reaction occurs from state $$n$$ is
**** $$W_{\gamma, \gamma'} (n)$$
*** For stoichiometric vectors $$\nu^\gamma = \{ \nu^{\gamma}_x \}$$ the difference between states $$\{n_x \}$$ and $$\{n_x * \nu^{\gamma}_x + \nu^{\gamma'}_x \}$$ induced by a given reaction from $$\gamma$$ to $$\gamma'$$ is defined as a generalized divergence
**** $$ \nabla_{\gamma' \gamma} = \nu^{\gamma} * \nu^{\gamma'}$$ a matrix that acts on functions of reactions and yields a variation of particle number
***** $$ (\nabla \lambda)_x = \sum_{\gamma' \gamma} (\nu^{\gamma}_x * \nu^{\gamma'}_x) \lambda_{\gamma' \gamma} $$
***** $$\nabla = \nu \mathfrak{d}$$
****** $$\mathfrak{d}$$ is the discrete divergence on the graph of complexes (incidence matrix) where $$\mathfrak{d}_{\gamma' \gamma} = \delta_{\gamma} * \delta_{\gamma'}$$
****** $$\nu$$ is the matrix containing stoichiometric coefficients acting on complexes and yielding particle numbers
**** $$(\nabla f)_{\gamma' \gamma} = \sum_x (\nu^{\gamma'}_x * \nu^{\gamma}_x)f_x$$ is the conjugate gradient mapping functions of the species to antisymmetric functions of the reactions
*** Master equation
**** $$d_t P(n) = \sum_{\gamma' \gamma} W_{\gamma' \gamma}(n + \nabla_{\gamma' , \gamma}) P(n + \nabla_{\gamma', \gamma}) * W_{\gamma' \gamma} (n) P(n)$$
**** $$d_t  | P \rangle = W | P \rangle$$
***** $$W = \sum_{\gamma' , \gamma , n} W_{\gamma' \gamma} (n) | n * \nabla_{\gamma' , \gamma} \rangle \langle n | * W_{\gamma' \gamma} (n) | n \rangle \langle n |$$
**** $$W_{\gamma' \gamma} (n) = k_{\gamma' \gamma} \prod_x \frac{[n_x]!}{[n_x * \nu^{\gamma}_{x}]!} V^{1-\sum_x \nu^{\gamma}_x}$$ is the __mass action__ prescription where the dependence on $$n$$ comes from the number of ways to choose the reactants for the complex serving as input to a reaction with __kinetic constant__ $$k_{\gamma' \gamma}$$ independent of $$n$$ and $$V$$
**** 
** B. Time-additive dynamical observables
** C. A caveat on conserved quantities
** D. Example
** E. Aside: Long-time large deviations
* III. Dynamical large deviation formalism
** A. Standard formalism
*** 1. Standard Lagrangian
*** 2. Equations of motion
*** 3. Standard Hamiltonian and Hamilton's equations
*** 4. Two-field picture
** B. Detailed formalism
*** 1. Detailed Lagrangian
*** 2. Equations of motion
*** 3. Detailed Hamiltonian and Hamilton's detailed equations
** C. Biased formalism
*** 1. Detailed biased dynamics
*** 2. Contraction of the currents and two-field picture
* IV. Stationary large deviations and dynamical phase transitions
** A. Boundary conditions
** B. Density-phase picture and global Hamiltonian attractors
** C. Conserved quantities in the two-field picture
** D. Generic dynamical phase transitions for multistable systems
* V. A few examples of dynamical phase transitions
** A. Schlogl model
** B. Generalized Schlogl model
** C. Runaway Schlogl model
* VI. Practical summary of formulae and results
* VII. Conclusion
* Appendix: Computations of the chemical Lagrangians and Hamiltonians
