#+setupfile: ./hugo_setup.org
#+hugo_slug: Logic_of_Worlds_Being_and_Event_by_Alain_Badiou_in_2009
#+TITLE: Logic of Worlds Being and Event by Alain Badiou in 2009
* [[file:philosophy.org][philosophy]], [[file:mathematics.org][mathematics]], [[file:Alain_Badiou.org][Alain Badiou]]
* pp. 535-536 note III.2
** Kant is the one author for whom I cannot feel any kinship. Everything in him exasperates me, above all his legalism—always asking Quid juris? or ‘Haven’t you crossed the limit?’—combined, as in today’s United States, with a religiosity that is all the more dismal in that it is both omnipresent and vague. The critical machinery he set up has enduringly poisoned philosophy, while giving great succour to the Academy, which loves nothing more than to rap the knuckles of the overambitious—something for which the injunction ‘You do not have the right!’ is a constant boon. Kant is the inventor of the disastrous theme of our ‘finitude’. The solemn and sancti* monious declaration that we can have no knowledge of this or that always foreshadows some obscure devotion to the Master of the unknowable, the God of the religions or his placeholders: Being, Meaning, Life. . . To render impracticable all of Plato’s shining promises—this was the task of the obsessive from Königsberg, our first professor.

Nevertheless, once he broaches some particular question, you are unfailingly obliged, if this question preoccupies you, to pass through him. His relentlessness—that of a spider of the categories—is so great, his delimitation of notions so consistent, his conviction, albeit mediocre, so violent, that, whether you like it or not, you will have to run his gauntlet.

Kant is a paradoxical philosopher whose intentions repel, whose style disheartens, whose institutional and ideological effects are appalling, but from whom there simultaneously emanates a kind of sepulchral greatness, like that of a great Watchman whose gaze you cannot escape, and who you can’t help fearing will entrap you into ‘demonstrating’ your speculative guilt, your metaphysical madness. That is why I approve of Lacan pairing him up with Sade (see ‘Kant avec Sade’, in Écrits). Sade is a laborious and compulsive writer, capable of turning blood-soaked eroticism into trite neo-classicism and sexual positions into botched acrobatics. Yet he abides, watching, surveying. He is the sad regent of debauchery, whose mandatory and sinister character he incessantly reveals.

I pay my tribute here to Kant’s philosophical sadism. In vain I seek to draw from this quibbling supervisor, always threatening you with detention, the authorization to platonize, that is, with regard to the critical incarceration (O, the eternal ‘limits’ of Reason!), the saving exit pass.
