#+setupfile: ./hugo_setup.org
#+hugo_slug: The_Structure_and_Interpretation_of_the_Standard_Model_by_Gordon_McCabe_in_2007
#+TITLE: The Structure and Interpretation of the Standard Model by Gordon McCabe in 2007
* see also
** [[file:Physics_and_geometry_by_Edward_Witten_in_1986.org][Physics and geometry by Edward Witten in 1986]]
* 1. Introduction
** in relativistic quantum theory the two basic types of thing which are represented to exist are matter fields and gauge force fields
** a matter field interacts locally with a gauge field, which then interacts locally elsewhere with other matter fields.
* 2. Matter fields
** Free matter fields are those which are idealized to be free from interaction with gauge force fields
** "matter field" and "particle" are often used interchangeably despite the fact they should be distinguished. the matter field is the primary object of consideration, and, if they exist at all, particles are derivative
** 2.1 The local space-time symmetry group
*** To specify the free elementary particles capable of existing in a universe, i.e., the free elementary ‘particle ontology,’ one specifies the projective, unitary, irreducible representations of a ‘local’ space–time symmetry group. However, because free particles are physical idealisations, one works backwards from the space–time symmetry group of interacting systems, and one bestows this symmetry group on free particles to ensure that when the idealisation is removed, and interactions are included, the space–time symmetry group is correct.
*** the space–time symmetry group of interacting particles is determined by which gauge fields exist, and the way in which matter fields couple to those gauge fields.
*** one specifies the free elementary particle ontology of our universe by specifying the ordinary, irreducible, unitary representations of $$SL(2, \mathbb{C}) \ltimes \mathbb{R}^{3,1}$$.
** 2.2 The configuration space approach
** 2.3 Curved space-time
** 2.4 The Wigner approach
** 2.5 Parity
** 2.6 Free particles in other universes
** 2.7 Natural bundles
** 2.8 Spinor bundles
** 2.9 Electrons and neutrinos
** 2.10 Particles and anti-particles
** 2.11 Fock space and second quantization
* 3. Gauge fields
** 3.1 Principal fibre bundles and G-structures
** 3.2 Classification of principal G-bundles
** 3.3 Gauge connections
** 3.4 Choice of gauge and gauge transformations
** 3.5 Gauge field curvature
** 3.6 The interaction bundle picture
* 4. Interactions
** 4.1 Interacting fields
*** Configuration space approach
**** A free particle of mass $$m$$ and spin $$s$$ represented by a cross-section $$\phi$$ of a spin-$$s$$ free-particle bundle $$\eta$$ must satisfy free field equations
***** $$\mathscr{P}(x, \phi(x), (\nabla^\eta \phi)(x), (\nabla^{\eta^2}\phi)(x), \ldots) = 0$$
***** where $$\mathscr{P}$$ is a polynomial expression, the mass $$m$$ is a coefficient in the polynomial, and $$\nabla^\eta$$ is the Levi-Civita connection on $$\eta$$
**** Free gauge fields represented by $$G$$-connections $$\nabla^\delta$$ on an interaction bundle $$\delta$$ must satisfy the free-field Yang-Mills equations
***** $$\nabla \cdot R^{\nabla^\delta} = 0$$
***** where $$R^{\nabla^\delta}$$ is the curvature two-form of the connection $$\nabla^\delta$$
***** $$G$$-connections on the interaction bundle $$\delta$$ correspond to smooth cross-sections of an affine bundle $$\mathscr{C}(\delta)$$
*** Interactions can be
**** 1) self
**** 2) boson field $$\phi$$ and fermion field $$\psi$$ interact via the Yukawa interaction
**** 3) a matter field can interact with a gauge field
***** $$\psi$$ is a cross-section of an interacting-particle bundle $$\alpha$$ 
***** $$\nabla^\delta$$ is a connection on the interaction bundle $$\delta$$
***** the pair $$(\psi, \nabla^\delta)$$ is a cross-section of the direct sum $$\alpha \oplus \mathscr{C}(\delta)$$ and it must satisfy coupled field equations consisting of
****** the interacting field equation upon the cross-sections $$\psi$$ of $$\alpha$$
******* $$\mathscr{P}(x, \psi(x), ( (\nabla^\eta \otimes \nabla^\delta) \phi)(x), ((\nabla^{\eta} \otimes \nabla^\delta)^2  \psi)(x), \ldots) = 0$$
****** the coupled Yang-Mills equation upon the curvature $$R^{\nabla^\delta}$$ of the connection on $$\delta$$
******* $$\nabla \cdot R^{\nabla^\delta} = C_0 J(\psi)$$
******* where $$C_0$$ is related to the coupling constants of the gauge field specifying the strength of the interaction
******* $$J(\psi)$$ is a $$4$$-current on $$\mathcal{M}$$, a cross-section of $$T^* \mathcal{M} \otimes \mathfrak{g}(\delta)$$
** 4.2 Interaction symmetries
** 4.3 The electroweak gauge connection bundle
** 4.4 The Higgs field
** 4.5 Minimal coupling
** 4.6 The Lagrangian approach
** 4.7 Quark colors
** 4.8 Quark mixing and the Cabibbo angle
** 4.9 The standard model Lagrangian
** 4.10 Gauge fields in other universes
** 4.11 Composite systems
** 4.12 Baryons, mesons, and hadron symmetries
** 4.13 Elementary particles and intrinsic properties
* 5. Standard model gauge groups and representations
** 5.1 The structure of compact groups
** 5.2 Standard model irreducible representations
** 5.3 The standard model gauge group
** 5.4 Duality and triality
** 5.5 The electroweak gauge group
** 5.6 The electromagnetic subgroup
* 6. The standard model interacting-particle bundle
** 6.1 Standard model electroweak-unified bundle
** 6.2 Standard model electroweak-broken bundle
* Appendices
** A. Topology
** B. Lie groups and Lie algebras
** C. Fibre bundles
** D. Representations of $$SL(2,\mathbb{C}) \ltimes \mathbb{R}^{3,1}$$ on $$\mathcal{F}(\mathcal{M},\mathbb{C}^n)$$
** E. The method of induced representation
** F. Canonical field quantization
** G. Photons and the Gupta-Bleuler technique
** H. Component expression of the curvature two-form
** I. Elementary particles in string theory
** J. The structure theorem for compact, connected Lie groups
** K. Irreducible representations of $$U(1)$$
** L. Non-integral charge and hypercharge
** M. Representations onto spaces tensored with $$\mathbb{C}^1$$
** N. Electroweak interaction bundles
