#+setupfile: ./hugo_setup.org
#+hugo_slug: The_pragmatic_turn_by_Richard_Bernstein_in_2010
#+TITLE: The pragmatic turn by Richard Bernstein in 2010
* 0. Preface
** introduction
*** on August 26th 1898 William James gave a talk at the philosophical union of the University of California at Berkeley he introduced pragmatism in his talk titled "philosophical conceptions and practical results"
*** when James tells us that he heard the principle of pragmatism enunciated in the 1870s he is referring to meetings of the metaphysical club and he specifically refers to Peirce's now famous 1878 paper "How to make our ideas clear"
*** Peirce's pragmatic maxim
**** consider what effects, which might conceivably have practical bearings, we conceive the object of our conception to have. then our conception of these effects is the whole of our conception of the object
*** 
** the cultural context
** The historical vicissitudes of pragmatism
** the global reach of pragmatism
** The German appropriation of pragmatic themes
** My intellectual journey with pragmatism
* 1. Charles S. Peirce's critique of cartesianism
** “Questions Concerning Certain Faculties Claimed for Man”; “Some Consequences of Four Incapacities”; and “Grounds of Validity of the Laws of Logic.” These articles, known as the “Cognition Series” are reprinted in Peirce 1992, pp. 11–82.”
** Peirce proceeds to list four contrasts between Cartesianism and scholasticism. He declares that, “without wishing to return to scholasticism, it seems to me that modern science and logic require us to stand upon a different platform from this” (ibid.). Here I will examine Peirce’s explication of his four critical points about the inadequacies of Cartesianism.
** “ There are beliefs that we take to be certain and indubitable. Our commonsense view is that there are numerous beliefs that we do not doubt and that provide “the bedrock of truth.” But Peirce’s commonsensism is a **critical** commonsensism. What is **indubitable** is not to be identified with what is **incorrigible**. As Peirce tells us, “what has been indubitable one day has often been proved on the morrow to be false” (5.514).5 We never escape from the situation of starting from some beliefs (prejudices and prejudgments) that we take to be indubitable. In this sense we can speak of a foundation from which any inquiry begins. 
** Peirce’s point is subtle and important. **He is an anti-foundationalist when foundationalism is understood as the doctrine that claims that there are basic or incorrigible truths that are not subject to revision.** But he is not denying – indeed, he is affirming – that **all knowing has a foundation in the sense that there are tacitly held beliefs, which we don’t doubt and take to be the bedrock of truth.** 
** Peirce would certainly endorse Wilfrid Sellars’s famous remark: “For empirical knowledge, like its sophisticated extension **science, is rational, not because it has a foundation**, but **because it is a self-correcting enterprise** which can put any claim in jeopardy, though not all at once” (Sellars 1997, p. 79).” 
** “In “How to Make Our Ideas Clear” Peirce declares: “The essence of belief is the establishment of a habit, and different beliefs are distinguished by the different modes of action to which they give rise” (Peirce 1992, pp. 129–30).”
** “Consider what effects, which might conceivably have practical bearings, we conceive the object of our conception to have. Then our conception of these effects is the whole of our conception of the object” (Peirce 1992, p. 132).”
* 2. The ethical consequences of William James's pragmatic pluralism
* 3. John Dewey's vision of radical democracy
* 4. Hegel and pragmatism
* 5. Pragmatism, objectivity, and truth
* 6. Experience after the linguistic turn
* 7. Hilary Putnam: The entanglement of fact and value
** 7.1 The context of Putnam's thesis
** 7.2 Cognitive values
** 7.3 Ethical and political values
** 7.4 Moral objectivity
* 8. [[file:Jurgen_Habermas.org][Jurgen Habermas]]'s Kantian pragmatism
** 8.1 Kant detranscendentalized
** 8.2 The epistemic normative rightness
** 8.3 Neither contextualism nor idealism
** 8.4 Moral rightness
** 8.5 Action and discourse
** 8.6 Moral constructivism and epistemological realism
** 8.7 Janus-Faced truth?
** 8.8 Moral constructivism again
** 8.9 Why Habermas rejects moral realism
* 9. [[file:Richard_Rorty.org][Richard Rorty]]'s deep humanism
** 9.1 Rorty's early metaphysical explorations
** 9.2 The linguistic turn
** 9.3 Doubts about analytic philosophy
** 9.4 Public liberalism and private irony
** 9.5 Rorty's humanism
** 9.6 Some doubts about Rorty's humanism
